apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-kubernetes
  namespace: hello-app


spec:

  replicas: 3


  selector:
    matchLabels:
      app: hello-kubernetes


  template:

    metadata:
      labels:
        app: hello-kubernetes


    spec:

      containers:

        - name: hello-container

          image: uday224/hello-kubernetes:v1

          ports:
            - containerPort: 8080